### ISSUE TITLE
Work around only for macs users

### ISSUE THREAD

**Issue by jakubsgit** [framer/framer-bridge-starter-kit#32]
Is this possible to make it on no macOS machines? 

I found the issue - I'll update this repo

This project needs to be opened in Framer X51 (old Framer) before the project will be built, and then possible to be opened in Current Framer Desktop 

You can update the file located at `design/document.json`, at the very bottom. Update the `version` to `75`, and make sure you open the file in the latest Framer Desktop (https://framer.com/desktop) 

From here, you should see the components in the project and get everything working. I'll update this repository to reflect the changes, and close the ticket in the meantime! Thanks for pointing this out.

_Originally posted by @addisonschultz in https://github.com/framer/framer-bridge-starter-kit/issues/30#issuecomment-746100998_

**Comment by addisonschultz** [comment]
At this point I don't think it's possible. The project needs to be opened in Framer Desktop app in order to have the right generated code to be packaged and shipped. 

We are working on a better solution for Windows users, but right now our Desktop offering is only on MacOS. 

One thing you could try, is on Framer Web, creating the components you need, downloading the file, compressing/renaming it to `.framerfx`, and then unzipping this version and running the build commands from there. I can't guarantee that will work, but there's a possibility. 

Hang tight in the meantime, as we have a lot better ways for sharing/exporting/publishing components coming in the near future that will be better than this setup almost entirely :)
