### ISSUE TITLE
do I need to have pro account to try Framer bridge on desktop app?

### ISSUE THREAD

**Issue by jakubsgit** [framer/framer-bridge-starter-kit#33]
As in the title. If it's needed in order to try your solution to have pro plan ?

**Comment by addisonschultz** [comment]
Hey there, you do need to have a Pro Plan in order to use the Desktop App. Keep in mind as well, that the desktop app is only available on MacOS at this point. 

If you're on Web, you can also invite the maximum editors to your team (2 editors), and you can start a Pro team trial from there if you'd like to test this feature before hand. Hopefully this helps! 

You can also feel free to join out Discord at https://framer.com/r/discord where you can ask questions into our community
